name: Commit Checks
run-name: ${{ github.ref }} - Commit Checks

on: push

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test-and-publish-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Install ZVM
        run: |
          curl https://raw.githubusercontent.com/tristanisham/zvm/master/install.sh | bash
          echo PATH="~/.zvm/self:~/.zvm/bin:$PATH" >> "$GITHUB_ENV"

      - name: Install Zig
        run: |
          zvm install master

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Test
        run: |
          zig build test

      - name: Build Docs
        run: |
          zig build docs

      - name: Setup GitHub Pages
        if: github.ref_name == 'main'
        uses: actions/configure-pages@v5

      - name: Upload GitHub Pages artifact
        if: github.ref_name == 'main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./zig-out/docs"

      - name: Deploy to GitHub Pages
        if: github.ref_name == 'main'
        id: deployment
        uses: actions/deploy-pages@v4
